language: java
install: ant jar
script:
  - bash ./dist/bin.sh install
  - cd ~
  - ~/Divvy/bin.sh start
  - sleep 30
  - |
    ~/Divvy/bin.sh -test 2>&1 |
    grep "Another Instance is Running" || { echo "Not Running"; exit 1; }
  - ~/Divvy/bin.sh stop
  - sleep 10
  - |
    ~/Divvy/bin.sh -test 2>&1 | 
    grep "Another Instance is Running" || { echo "Still Running"; exit 1; }
  - echo "Running and Stopping Working Fine";

os:
  - linux
jdk:
  - oraclejdk8
  - openjdk8
  - openjdk7
